# Generated by Django 4.1.3 on 2023-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userNameLoc', models.CharField(max_length=50, unique=True, verbose_name='사용자이름(한국어)')),
                ('userNameGbl', models.CharField(max_length=50, unique=True, verbose_name='사용자이름(영어)')),
                ('telNo', models.CharField(blank=True, max_length=64, verbose_name='전화번호')),
                ('telCountryCode', models.CharField(default='+82', max_length=20, verbose_name='전화국가번호')),
                ('email', models.EmailField(max_length=256, verbose_name='이메일주소')),
                ('regDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='계정 생성일')),
                ('regUserIP', models.CharField(max_length=20, null=True, verbose_name='계정 생성IP')),
                ('userCode', models.CharField(default='U', max_length=1, verbose_name='사용자 구분')),
                ('userStatus', models.CharField(max_length=1, verbose_name='사용자 상태')),
                ('pwErrCount', models.IntegerField(default=0, verbose_name='비밀번호 실패횟수')),
                ('last_loginIP', models.CharField(default=False, max_length=20, verbose_name='마지막 접속IP')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('is_active', models.BooleanField(default=True, verbose_name='로그인 가능')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
