# Generated by Django 4.1.3 on 2023-01-09 08:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='로그인한 IP')),
                ('country', models.CharField(max_length=255, verbose_name='로그인한 국가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='로그인 기록')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
