# Generated by Django 4.1.3 on 2023-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='사용자ID')),
                ('setTitle', models.CharField(max_length=50, verbose_name='퀴즈 세트 타이틀')),
                ('publicYn', models.CharField(max_length=1, verbose_name='공개여부')),
                ('regDate', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('regUser', models.CharField(max_length=20, verbose_name='등록 유저')),
                ('regUserIP', models.CharField(max_length=20, verbose_name='등록 유저IP')),
                ('chgDate', models.DateTimeField(auto_now=True, verbose_name='변경일자')),
                ('chgUser', models.CharField(max_length=20, verbose_name='변경 유저')),
                ('chgUserIP', models.CharField(max_length=20, verbose_name='변경 유저IP')),
            ],
        ),
        migrations.CreateModel(
            name='Set_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=20, verbose_name='세트ID')),
                ('libID', models.CharField(max_length=20, verbose_name='라이브러리ID')),
                ('regDate', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('chgData', models.DateTimeField(auto_now=True, verbose_name='변경일자')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='사용자ID')),
                ('quizTitle', models.CharField(max_length=200, verbose_name='퀴즈 제목')),
                ('quizDetail', models.CharField(max_length=500, verbose_name='퀴즈 지문')),
                ('quizTime', models.IntegerField(verbose_name='풀이시간')),
                ('category', models.CharField(max_length=8, verbose_name='퀴즈 카테고리')),
                ('quizChar', models.CharField(max_length=2, verbose_name='퀴즈 캐릭터')),
                ('quizNo', models.CharField(max_length=4, verbose_name='퀴즈 넘버')),
                ('quizType', models.CharField(max_length=1, verbose_name='퀴즈 타입')),
                ('answerCount', models.IntegerField(verbose_name='정답 개수')),
                ('quizValue1', models.CharField(max_length=50, verbose_name='퀴즈 값1')),
                ('quizValue2', models.CharField(max_length=50, verbose_name='퀴즈 값2')),
                ('quizValue3', models.CharField(max_length=50, verbose_name='퀴즈 값3')),
                ('quizValue4', models.CharField(max_length=50, verbose_name='퀴즈 값4')),
                ('quizValue5', models.CharField(max_length=50, verbose_name='퀴즈 값5')),
                ('regDate', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('chgDate', models.DateTimeField(auto_now=True, verbose_name='변경일자')),
                ('quizSet', models.ManyToManyField(related_name='set_quiz', to='quiz.set', verbose_name='퀴즈 세트ID')),
            ],
        ),
    ]
